In [269]:
# Regresión Bosques Aleatorios

# Cómo importar las librerías
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [270]:
dataset = pd.read_excel('./Material/Datasets/Modelo 1.xlsx',sheet_name='Sheet3')

In [271]:
dummy_variables1 = pd.get_dummies(dataset['Plant'])
dummy_variables2 = pd.get_dummies(dataset['Route'])
dummy_variables3 = pd.get_dummies(dataset['Sold To Name'])
dummy_variables4 = pd.get_dummies(dataset['BU'])

In [272]:
dummy_variables4

,0,Accesories,Business PC Solutions (BPS),Large Format,Office Printing Solutions (OPS),Supplies
0,0,0,0,0,0,1
1,0,0,0,0,0,1
2,0,0,0,0,0,1
3,0,0,0,0,1,0
4,0,0,0,0,1,0
...,...,...,...,...,...,...
1488,0,0,0,0,0,1
1489,0,0,0,0,0,1
1490,0,0,0,0,0,1
1491,0,0,0,0,0,1
1492,0,0,0,0,0,1

In [273]:
dataset = pd.concat([dataset, dummy_variables1,dummy_variables2,dummy_variables3,dummy_variables4], axis=1)

In [274]:
dataset['time']=dataset['tiempo de entrega']

In [275]:
dataset.drop(['Plant','Sold To Name','Route','tiempo de entrega','BU'],inplace=True,axis=1)

In [276]:
dataset.shape

(1493, 70)

In [277]:
X = dataset.iloc[:, 1:69].values
y = dataset.iloc[:, 69].values

In [278]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [279]:
X

array([[2.00000000e+01, 5.63160000e+03, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.00000000e+00, 4.42840000e+02, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.00000000e+00, 1.10810000e+03, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       ...,
       [1.30000000e+02, 1.54604271e+04, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [2.55000000e+02, 3.63349500e+04, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00],
       [1.80000000e+02, 4.80536645e+04, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.00000000e+00]])

In [280]:
dataset

,Delivery,Actual Quant Delvrd,Net value USD,US21,US22,US23,US27,US38,4U10CO,4U11CO,...,UNIVERSIDAD DE LA SABANA,VENEPLAST LTDA,ZOFICOL SAS,0,Accesories,Business PC Solutions (BPS),Large Format,Office Printing Solutions (OPS),Supplies,time
0,8028333983,20,5631.600000,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,18
1,8028409605,2,442.840000,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,16
2,8028063213,2,1108.100000,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,24
3,8028080883,1,3822.500000,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,75
4,8028098914,30,144324.880000,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1488,8027581970,420,7670.075368,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,7
1489,8027601541,60,1054.805684,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,7
1490,8027601613,130,15460.427074,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,7
1491,8027657008,255,36334.950000,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,6
1492,8027818086,180,48053.664537,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,6

In [281]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

In [282]:
from sklearn.ensemble import RandomForestRegressor
regression = RandomForestRegressor(n_estimators = 2000, random_state=42)
regression.fit(X_train,y_train)

RandomForestRegressor(n_estimators=2000, random_state=42)

In [283]:
y_train

array([36, 34, 21, ..., 17, 10, 12], dtype=int64)

In [284]:
y_predi = regression.predict(X_test)

In [285]:
y_predi

array([67.38718452, 15.1915    , 29.55316667, 21.94388333, 20.3935    ,
       14.26363929, 38.50566667, 70.97032381, 34.28575   , 14.69714139,
       18.098525  , 32.39131667, 14.95      , 42.98550734, 59.91871667,
       31.36583333, 15.26875   , 13.2743    , 12.21227857, 17.67762024,
       32.19879167, 32.21616667, 22.0095    , 20.7665    , 12.95238333,
       26.78766667, 13.81833333, 18.02476667, 13.99458333, 15.63430476,
       35.2825    , 20.36791667, 62.24569643, 24.74987143, 29.1515    ,
       27.92778333, 17.713     , 28.71175   , 30.0495    , 21.87666667,
       12.23996548, 33.79831786, 23.40725   , 19.143     , 16.87630532,
       29.55316667, 11.34241667, 11.4295    ,  9.90049524, 19.89343452,
       31.96421071, 35.33241667, 14.33907976, 10.981     , 13.32765714,
       22.3415    , 21.0205    , 11.2855    , 16.63694881, 16.50618214,
       11.1925    , 20.202     , 12.30116667, 47.788375  , 18.1235    ,
       11.90589048, 10.49325   , 19.42913095, 20.9165    , 21.707     ,
       38.232     , 15.035     , 16.21701012, 56.70362222, 26.18925   ,
       19.5485    , 14.368     , 14.66604167, 17.74891667, 11.339     ,
       88.9825    , 28.47984246, 36.52285714,  7.835     , 10.8815    ,
       17.40649167, 11.44935   , 15.74567143, 25.185625  , 19.47391667,
       12.0295    , 24.644875  , 87.2391    , 13.5985    , 16.81745833,
       45.96568333, 32.611     , 12.11982857, 13.0708    , 54.42691503,
       13.35784524, 17.8750373 , 35.86229167, 25.02591667, 10.8435    ,
       11.0875    , 12.5941256 , 13.931125  , 27.90252381, 22.79216667,
       10.87833333, 20.67925   , 70.97232381, 19.96940139, 74.46394616,
       56.45554167, 19.49189583, 16.28595833, 10.7715    , 27.929     ,
       22.99726667, 22.45914524, 18.345     , 13.67624167, 35.19371667,
       24.74987143, 12.43716667, 22.135925  ,  9.88309583, 38.15983333,
       10.4165    , 23.81472976, 34.646     , 49.685375  , 55.71812222,
       46.23318333, 70.51174306, 85.40141667, 22.19325   , 59.36502163,
       17.056     , 30.77192123, 15.74203631, 15.64927778, 31.27883333,
       15.39315833, 34.37491667, 19.03832143, 35.53640833, 19.597925  ,
       12.2205    , 18.818     , 18.93843214, 19.23304167, 12.085175  ,
       20.054375  , 20.02160714, 15.49354881, 30.147     , 13.16703333,
       15.6499119 , 20.43692857, 12.949     , 24.16491667, 24.78383333,
       15.96700595, 35.19371667, 17.94836905, 24.71225   , 12.89897381,
       13.98054167, 38.0645    , 32.32103571, 21.8735    , 91.2265    ,
       30.357     , 18.5434    , 25.17512976, 14.62773333, 27.23116667,
       19.5605    , 12.30748333, 44.92875714,  9.52255952, 17.73586071,
       25.24603333, 88.99      , 16.87630532, 15.49354881, 16.89759167,
       20.32982143, 21.20668182, 21.997     , 31.901     , 35.403     ,
       21.45165   , 22.67718552, 17.87116667, 18.70439762, 19.245125  ,
       12.55594167, 32.1925    , 16.24678988, 10.89595833, 33.16183532,
       30.29075   , 31.36583333, 16.54275   , 32.67578075, 35.16122262,
       11.26625   , 30.37927857, 12.54439167, 22.783625  , 27.0485    ,
       54.9321881 , 32.29603571, 34.3427381 , 43.05820714, 18.60505   ,
       13.56945833, 30.4215    , 22.749125  , 20.108     , 61.47254138,
       14.39520417, 16.83553214, 19.37678333, 60.85590128, 88.48      ,
       20.714     , 29.88745536, 12.1205    , 44.14272798, 13.74867262,
       12.482875  , 32.86575   , 20.74391667, 14.368     , 16.61975   ,
       23.70779167, 14.54822799, 25.01020675, 10.5535    , 14.52816032,
       29.04983333, 11.22391667, 12.816     , 17.23698214, 88.99      ,
       25.7555    , 34.268     , 28.47984246, 24.52972937, 12.1060631 ,
        9.49916667, 14.781     , 10.4415    , 11.2078    , 68.86020313,
       12.74513333, 84.88733333, 11.13669643, 10.703     , 68.19042857,
       21.8345    , 14.81466667, 12.21227857, 15.74203631, 68.36614187,
       21.11866667, 15.87499167, 11.2525    , 34.603475  , 84.93516667,
       17.65716667, 33.01283333, 21.16783333, 22.46625   , 11.95085   ,
       19.70425   , 29.78075   , 20.10153481, 19.858     , 30.4725    ,
       10.35925   , 48.42233333, 35.39668214, 13.54090833, 10.390875  ,
       17.85320833, 68.76513333, 32.214375  , 34.956     , 24.3807119 ,
       32.29603571, 30.11059167, 10.8985    , 40.728125  ])

In [286]:
from sklearn.metrics import r2_score
# obtener predicciones para el conjunto de prueba
y_pred = regression.predict(X_test)
# calcular R2
r2 = r2_score(y_test, y_pred)
print('R2:', r2)

R2: 0.7093184735746574

In [287]:
from sklearn.metrics import mean_squared_error

# obtener predicciones para el conjunto de prueba
y_pred = regression.predict(X_test)

# calcular MSE
mse = mean_squared_error(y_test, y_pred)

print('MSE:', mse)

MSE: 103.6163224081782

In [288]:
dataset.to_excel('p.xlsx',index=False)

In [ ]:
df = pd.DataFrame(y_predi, columns=['Columna 1'])
df2 = pd.DataFrame(y_test)

In [ ]:
df.to_excel('k.xlsx')
df2.to_excel('f.xlsx')